In [2]:
import numpy as np
np.random.seed(42)

a = np.random.randn(5)
print(a)

array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337])

In [3]:
z = np.random.uniform(-1/np.sqrt(784), 1/np.sqrt(784), 5)
print(z)

array([-0.03156546,  0.02615544,  0.0072225 ,  0.01486233, -0.03424396])

In [7]:
def relu(x):
    return np.maximum(0, x)

In [10]:
a = np.array([[1,2], [4,5]])
b = np.array([2,3])
c = a-b
z = relu(c)
print(z)

array([[0, 0],
       [2, 2]])

In [11]:
x_train = np.array([1,2,3,4,5,6,7,8,9])
x_train = x_train.reshape(x_train.shape[0], -1)
print(x_train)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [16]:
zeros_array = np.zeros((2, 3, 4))
print(zeros_array.shape)
zeros_array = zeros_array.reshape(zeros_array.shape[0], -1)
print(zeros_array.shape)

(2, 3, 4)
(2, 12)


In [19]:
# Onehot encoding
y = np.array([2,7,3,5,6,8,2,4,5,3,2])
num_classes = 10
print(np.eye(num_classes)[y])
print(np.eye(num_classes))

[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [24]:
y = np.array([2,7,3,5,6,8,2,4,5,3,2])
permutation = np.random.permutation(y.shape[0])
y = permutation
y

array([10,  9,  4,  6,  5,  7,  8,  1,  3,  0,  2], dtype=int32)

In [34]:
a = np.array([[0,0,1,0,0], [1,0,0,0,0]])
a = np.argmax(a, axis=1)
predictions = np.array([[0,0,1,0,0], [0,0,0,0,1]])
predictions = np.argmax(predictions, axis = 1)
accuracy = np.mean(predictions == a)
print(accuracy)
print(a)
print(predictions)

0.5
[2 0]
[2 4]
